name: Flask CI/CD Pipeline - Lab 12

on:
  push:
    branches:
      - ino_dev
  pull_request:
    branches:
      - ino_dev

jobs:
  pipeline_execute:
    runs-on: ubuntu-latest

    steps:
      - name: STAGE Setup
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test,async]
          pip install pytest

      - name: Run pytest validation
        run: |
          pytest
        continue-on-error: true

      - name: STAGE Publish - Budowanie artefaktu .whl oraz źródłowego
        run: |
          python -m build

      - name: STAGE Publish - Załączanie artefaktu
        uses: actions/upload-artifact@v4
        with:
          name: flask-distributable-package
          path: dist/
          retention-days: 5
